-- ====================================================================
-- LAWYER DATABASE SCHEMA (PHASE 2 — UPDATED)
-- This script creates all tables for the Legal Intelligence Platform.
-- Includes: lawyers, cases, judges, law_firms
-- Run this script in the Supabase SQL Editor.
-- ====================================================================

-- Drop tables in correct dependency order (child tables first)
DROP TABLE IF EXISTS cases;
DROP TABLE IF EXISTS lawyers;
DROP TABLE IF EXISTS judges;
DROP TABLE IF EXISTS law_firms;

-- ====================================================================
-- 1. Create the 'law_firms' table
-- ====================================================================
CREATE TABLE law_firms (
    -- Unique ID for each law firm, automatically incremented
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Official name of the law firm
    name text NOT NULL,

    -- City where the firm is headquartered
    city text NOT NULL DEFAULT 'Cuttack',

    -- Practice specialties the firm is known for (comma-separated)
    specialties text,

    -- Year the firm was established
    established_year integer,

    -- Number of advocates currently associated with the firm (denormalized for quick display)
    advocate_count integer NOT NULL DEFAULT 0,

    -- Short profile / overview of the firm
    description text,

    -- Phone number for the firm
    phone text,

    -- Email address for the firm
    email text
);

-- ====================================================================
-- 2. Create the 'judges' table
-- ====================================================================
CREATE TABLE judges (
    -- Unique ID for each judge, automatically incremented
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Judge's full name with honorific (e.g. "Hon'ble Justice Surya Kant")
    name text NOT NULL,

    -- Court where this judge presides
    court text NOT NULL DEFAULT 'Odisha High Court',

    -- Bench type (e.g. "Division Bench", "Single Bench", "District Court")
    bench_type text NOT NULL DEFAULT 'Single Bench',

    -- District name for district court judges (NULL for High Court)
    district text,

    -- Year the judge was appointed to their current position
    appointment_year integer,

    -- Total cases heard by this judge (denormalized for quick display)
    total_cases integer NOT NULL DEFAULT 0,

    -- Average disposal time across all cases (in months)
    avg_disposal_time numeric(4,1) NOT NULL DEFAULT 0.0,

    -- Whether the judge is currently active/sitting
    is_active boolean NOT NULL DEFAULT true,

    -- Area of legal specialization (e.g. "Constitutional", "Criminal", "Tax")
    specialization text
);

-- ====================================================================
-- 3. Create the 'lawyers' table (Phase 2 — adds firm_id)
-- ====================================================================
CREATE TABLE lawyers (
    -- Unique ID for each lawyer, automatically incremented
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Lawyer's full name
    name text NOT NULL,

    -- Bar Council registration number, must be unique
    bar_number text UNIQUE NOT NULL,

    -- Practice areas (e.g., "Property, Civil, Constitutional")
    practice_area text NOT NULL,

    -- Years of professional experience
    experience integer NOT NULL DEFAULT 0,

    -- Contact details
    phone text,
    email text,

    -- Lawyer's location/city (defaulting to Cuttack where Odisha High Court is based)
    city text NOT NULL DEFAULT 'Cuttack',

    -- AI-generated analysis summary of the lawyer's recent court activity and specialization
    ai_insight text,

    -- Average disposal time of cases in months (e.g. 7.2)
    avg_disposal_time numeric(4,1) NOT NULL DEFAULT 0.0,

    -- Court level where the advocate primarily practices
    -- "High Court" = Odisha High Court | "District Court" = any district court
    court_level text NOT NULL DEFAULT 'High Court' CHECK (court_level IN ('High Court', 'District Court')),

    -- Foreign key linking this lawyer to a law firm (optional)
    firm_id bigint REFERENCES law_firms(id) ON DELETE SET NULL
);

-- ====================================================================
-- 4. Create the 'cases' table (Phase 2 — adds judge_id)
-- ====================================================================
CREATE TABLE cases (
    -- Unique ID for each case, automatically incremented
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Link (foreign key) connecting a case to a specific lawyer.
    -- If the lawyer is deleted, their cases are automatically deleted (ON DELETE CASCADE).
    lawyer_id bigint REFERENCES lawyers(id) ON DELETE CASCADE NOT NULL,

    -- Case identifier (e.g., "WP(C)/1234/2023")
    case_number text NOT NULL,

    -- The court handling the case (defaulting to Odisha High Court)
    court text NOT NULL DEFAULT 'Odisha High Court',

    -- Type of case (e.g., "Writ Petition", "Criminal Appeal", "Civil Suit")
    case_type text NOT NULL,

    -- Date when the case was filed
    filing_date date NOT NULL DEFAULT CURRENT_DATE,

    -- Status of the case (can only be 'Pending' or 'Disposed')
    status text NOT NULL CHECK (status IN ('Pending', 'Disposed')),

    -- Detailed outcome category (Pending for active cases, and legal outcomes for disposed cases)
    outcome text NOT NULL CHECK (outcome IN ('Pending', 'Allowed', 'Dismissed', 'Partly Allowed', 'Withdrawn', 'Transferred')),

    -- Brief description of the final order or judgment
    judgment text,

    -- Foreign key linking this case to a presiding judge (optional)
    judge_id bigint REFERENCES judges(id) ON DELETE SET NULL
);

-- ====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Public read/write access for all four tables.
-- ====================================================================

-- Enable RLS on all tables
ALTER TABLE law_firms ENABLE ROW LEVEL SECURITY;
ALTER TABLE judges ENABLE ROW LEVEL SECURITY;
ALTER TABLE lawyers ENABLE ROW LEVEL SECURITY;
ALTER TABLE cases ENABLE ROW LEVEL SECURITY;

-- Policies for 'law_firms' table
CREATE POLICY "Allow public select on law_firms" ON law_firms FOR SELECT USING (true);
CREATE POLICY "Allow public insert on law_firms" ON law_firms FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on law_firms" ON law_firms FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on law_firms" ON law_firms FOR DELETE USING (true);

-- Policies for 'judges' table
CREATE POLICY "Allow public select on judges" ON judges FOR SELECT USING (true);
CREATE POLICY "Allow public insert on judges" ON judges FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on judges" ON judges FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on judges" ON judges FOR DELETE USING (true);

-- Policies for 'lawyers' table
CREATE POLICY "Allow public select on lawyers" ON lawyers FOR SELECT USING (true);
CREATE POLICY "Allow public insert on lawyers" ON lawyers FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on lawyers" ON lawyers FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on lawyers" ON lawyers FOR DELETE USING (true);

-- Policies for 'cases' table
CREATE POLICY "Allow public select on cases" ON cases FOR SELECT USING (true);
CREATE POLICY "Allow public insert on cases" ON cases FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on cases" ON cases FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on cases" ON cases FOR DELETE USING (true);
